# Generated by Django 4.1.7 on 2023-02-20 10:14

import attachments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=2550, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='ссылка')),
                ('attachment_file', models.FileField(upload_to=attachments.models.attachment_upload, verbose_name='файл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachments.onlinematerialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Полезный материал',
                'verbose_name_plural': 'Полезные материалы',
                'ordering': ['-modified'],
            },
        ),
    ]
