# Generated by Django 4.1.7 on 2023-03-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_club_club_id'),
        ('attachments', '0005_alter_attachment_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinematerialcategory',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.club', verbose_name='Клуб'),
        ),
    ]
