# Generated by Django 4.1.7 on 2023-02-22 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('sort', models.IntegerField(blank=True, default='', verbose_name='Сортировка')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='название')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='телефон')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='адрес')),
                ('vk_news_domain', models.CharField(blank=True, default='', max_length=100, verbose_name='группа ВК')),
                ('vk_post_header', models.CharField(blank=True, default='', max_length=100)),
                ('news_token', models.CharField(blank=True, default='', max_length=500, verbose_name='Access token для новостей')),
                ('fb_news_domain', models.CharField(blank=True, default='', max_length=100, verbose_name='группа Facebook')),
                ('instagram', models.CharField(blank=True, default='', max_length=1000, verbose_name='инстаграм')),
                ('twitter', models.CharField(blank=True, default='', max_length=1000, verbose_name='твитер')),
                ('website', models.CharField(blank=True, default='', max_length=1000, verbose_name='сайт')),
                ('work_hours', models.TextField(blank=True, default='', verbose_name='время работы')),
                ('latitude', models.FloatField(blank=True, default=0, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, default=0, verbose_name='долгота')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('display_text', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number_formatted', models.CharField(blank=True, default='', max_length=100)),
                ('oferta_url', models.URLField(blank=True, default='', max_length=100)),
                ('contacts_line_image', models.CharField(blank=True, default='', max_length=100)),
                ('crm_id', models.CharField(blank=True, default='', max_length=1000, verbose_name='id crm')),
                ('bank_info', models.CharField(blank=True, default='', max_length=255)),
                ('show_in_mobile_settings', models.BooleanField(default=True, verbose_name='Показывать в мобильный настройках')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='ApiKey для push сервиса')),
                ('logo', models.ImageField(blank=True, default='', upload_to=organization.models.get_image_path, verbose_name='Лого')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Администрация клуба'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='администратор')),
            ],
            options={
                'verbose_name': 'клуб',
                'verbose_name_plural': 'клубы',
            },
        ),
    ]
