# Generated by Django 4.1.7 on 2023-03-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_club_api_key_remove_club_bank_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='club_id клуба'),
        ),
    ]
