#!/bin/bash

dirs=(
    "Dashboard"
    "Entrance"
    "Notifications"
    "Profile"
    "Promotions"
    "Schedule"
    "Team"
    "analytics"
    "appointments"
    "atol"
    "attachments"
    "banners"
    "base"
    "call_integration"
    "chat"
    "client"
    "goods"
    "info"
    "integration"
    "log"
    "ndflka"
    "news"
    "notes"
    "organization"
    "payment"
    "polls"
    "settings"
    "sights"
    "sms"
    "staff"
    "timetable"
    "trainer"
    "work"
)

for dir in "${dirs[@]}"
do
    mkdir "$dir/migrations"
    touch "$dir/migrations/__init__.py"
    chmod 777 -R "$dir/migrations"
done