# Generated by Django 4.1.7 on 2023-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Название баннера')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Многострочное описание баннера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение баннера')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
