# Generated by Django 4.1.7 on 2023-03-23 08:20

import banners.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_club_club_id'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersmodel',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.club', verbose_name='Привязка к клубу'),
        ),
        migrations.AlterField(
            model_name='bannersmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=banners.models.banner_upload, verbose_name='Изображение баннера'),
        ),
    ]
