# Generated by Django 4.1.7 on 2023-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_bannersmodel_club_alter_bannersmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersmodel',
            name='sort',
            field=models.IntegerField(default=500, verbose_name='Сортировка'),
        ),
    ]
